### ISSUE TITLE
train_generator.py

### ISSUE THREAD

**Issue by Tuxius** [maxpumperla/deep_learning_and_the_game_of_go#32]
Dear all,

I am getting an error trying to run the example code from chapter 7 "train_generator.py". I downloaded the github repository and got the following error after running with python 2.7.12:

`KGS-2003-19-7582-.tar.gz 7582
KGS-2002-19-3646-.tar.gz 3646
KGS-2001-19-2298-.tar.gz 2298
total num games: 179689
Drawn 100 samples:
Traceback (most recent call last):
  File "train_generator.py", line 22, in <module>
    generator = processor.load_go_data('train', num_games, use_generator=True)  # <3>
  File "/mnt/sambashare/deep_learning_and_the_game_of_go-master/code/dlgo/data/parallel_processor.py", line 46, in load_go_data
    self.map_to_workers(data_type, data)  # <1>
  File "/mnt/sambashare/deep_learning_and_the_game_of_go-master/code/dlgo/data/parallel_processor.py", line 189, in map_to_workers
    _ = p.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: unbound method __new__() must be called with Sgf_game instance as first argument (got classobj instance instead)
`
It seems that something with the parallel workers doesn't work, a topic not covered in the book. Any idea?

Best

**Comment by Tuxius** [comment]
Solution: Use Python 3.5.2
