### ISSUE TITLE
Chapter 4 crashes when entering a coordinate while player against mcts

### ISSUE THREAD

**Issue by olbrichj** [maxpumperla/deep_learning_and_the_game_of_go#47]
`python mcts_go.py` and entering the first coordinate results in:
```
Traceback (most recent call last):
  File "mcts_go.py", line 47, in <module>
    main()
  File "mcts_go.py", line 41, in main
    move = bot.select_move(game)
  File "/Users/xxx/Downloads/deep_learning_and_the_game_of_go-chapter_4/code/dlgo/mcts/mcts.py", line 109, in select_move
    winner = self.simulate_random_game(node.game_state)
  File "/Users/xxx/Downloads/deep_learning_and_the_game_of_go-chapter_4/code/dlgo/mcts/mcts.py", line 165, in simulate_random_game
    Player.black: agent.FastRandomBot(),
AttributeError: module 'dlgo.agent' has no attribute 'FastRandomBot'
```

This is just a downloaded version of the provided repository.

**Comment by computer-idol** [comment]
话说你运行的时候速度怎么样？多少秒一步？
