### ISSUE TITLE
пункт 3.4. Исправил в bot_v_bot.py from dlgo import goboard_slow

### ISSUE THREAD

**Issue by puteets66066** [maxpumperla/deep_learning_and_the_game_of_go#51]

**Comment by puteets66066** [comment]
Исправил в bot_v_bot.py
from dlgo import goboard_slow
game = goboard_slow.GameState.new_game(board_size)

C:\Users\Юра>python bot_v_bot.py
Traceback (most recent call last):
  File "bot_v_bot.py", line 28, in <module>
    main()
  File "bot_v_bot.py", line 14, in main
    gotypes.Player.black: agent.naive.RandomBot(),
AttributeError: module 'dlgo.agent' has no attribute 'naive'

**Comment by puteets66066** [comment]
#from dlgo import agent
from dlgo.agent import naive
#from dlgo import goboard
from dlgo import goboard_slow
from dlgo import gotypes
from dlgo.utils import print_board, print_move
import time


def main():
    board_size = 9
#    game = goboard.GameState.new_game(board_size)
    game = goboard_slow.GameState.new_game(board_size)
    bots = {
        gotypes.Player.black: naive.RandomBot(),
        gotypes.Player.white: naive.RandomBot(),
    }
#    bots = {
#        gotypes.Player.black: agent.naive.RandomBot(),
#        gotypes.Player.white: agent.naive.RandomBot(),
#    }
    while not game.is_over():
        time.sleep(0.3)  

        print(chr(27) + "[2J")  # <2>
        print_board(game.board)
        bot_move = bots[game.next_player].select_move(game)
        print_move(game.next_player, bot_move)
        game = game.apply_move(bot_move)


if __name__ == '__main__':
    main()

**Comment by puteets66066** [comment]
from dlgo.agent import naive
from dlgo import goboard_slow
bots = {
        gotypes.Player.black: naive.RandomBot(),
        gotypes.Player.white: naive.RandomBot(),
    }

Так исправил файл bot_v_bot.py. Чтобы он заработал в конце пункта 3.4
Corrects file  bot_v_bot.py. To make it work at the end of point 3.4
