### ISSUE TITLE
chapter 13 alphago_policy_sl.py

### ISSUE THREAD

**Issue by activate-an** [maxpumperla/deep_learning_and_the_game_of_go#65]
when i run alphago_policy_sl.py  i will get an error ,if anybody can help me.

Epoch 1/200
Traceback (most recent call last):
  File "E:/13beifen/code/example/alphago_policy_sl.py", line 51, in <module>
    main( )
  File "E:/13beifen/code/example/alphago_policy_sl.py", line 37, in main
    callbacks=[ModelCheckpoint('../checkpoints/alphago_sl_policy_{epoch}.h5')]
  File "D:\Anaconda3\envs\deep\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\deep\lib\site-packages\keras\engine\training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\Anaconda3\envs\deep\lib\site-packages\keras\engine\training_generator.py", line 229, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "D:\Anaconda3\envs\deep\lib\site-packages\keras\callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "D:\Anaconda3\envs\deep\lib\site-packages\keras\callbacks.py", line 336, in on_epoch_end
    self.progbar.update(self.seen, self.log_values)
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'

Process finished with exit code 1

**Comment by maxpumperla** [comment]
@activate-an check out this thread: https://github.com/keras-team/keras/issues/3657
it's quite possible that your data is empty or some attributes set incorrectly.

**Comment by activate-an** [comment]
thank you @maxpumperla  ,This problem has been solved, thank you very much
